# All values in this document are the ENVIRONMENT variable names that can override the defaults
# from `default.yaml`
---
ecosystem:
  store: ECOSYSTEM_STORE
queue:
  redisConnection:
    host: REDIS_HOST
    port: REDIS_PORT
    options:
      password: REDIS_PASSWORD
      tls: REDIS_TLS_ENABLED
    database: REDIS_DB_NUMBER
  prefix: REDIS_QUEUE_PREFIX
